quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY:sk-or-v1-7622f2ca22023...3a}
quarkus.langchain4j.openai.base-url=https://openrouter.ai/api/v1
quarkus.langchain4j.openai.timeout=PT15S
quarkus.langchain4j.openai.max-retries=1
quarkus.langchain4j.openai.chat-model.model-name=${OPENAI_MODEL:openai/gpt-oss-120b:free}
rag.graph.enabled=true
rag.retrieve.top-k=50
rag.retrieve.rrf-k=20
rag.retrieve.similarity-ratio=0.6

